create table app_users (
    id bigint generated by default as identity primary key,
    username varchar(64) not null unique,
    password_hash varchar(255) not null,
    full_name varchar(255) not null,
    role varchar(32) not null,
    enabled boolean not null default true,
    created_at timestamp with time zone not null
);

create table licenses (
    id bigint generated by default as identity primary key,
    user_id bigint not null references app_users(id) on delete cascade,
    license_key varchar(128) not null unique,
    certificate_number bigint not null,
    active boolean not null default true,
    issued_at timestamp with time zone not null,
    expires_at timestamp with time zone
);

create table refresh_tokens (
    id bigint generated by default as identity primary key,
    token_id varchar(64) not null unique,
    user_id bigint not null references app_users(id) on delete cascade,
    created_at timestamp with time zone not null,
    expires_at timestamp with time zone not null,
    revoked_at timestamp with time zone
);

create index idx_licenses_user_id on licenses(user_id);
create index idx_refresh_tokens_user_id on refresh_tokens(user_id);
create index idx_refresh_tokens_expires_at on refresh_tokens(expires_at);
